language: erlang
otp_release:
  - 19.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - sudo pip install codecov
script:
  - ./rebar3 compile
  - ./rebar3 eunit
  - ./rebar3 cover
  - ./rebar3 covertool generate
  - cp _build/test/covertool/tsoder.covertool.xml ./cobertura.xml
after_success:
  - codecov
