language: erlang
otp_release:
  - 18.3
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
before_script:
  - kerl list installations
script:
  - ./rebar3 compile
  - ./rebar3 eunit
